services:
  postgres:
    image: postgres:16-alpine
    container_name: bifrost-postgres
    environment:
      POSTGRES_USER: bifrost
      POSTGRES_PASSWORD: bifrost_password
      POSTGRES_DB: bifrost
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bifrost -d bifrost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - bifrost_network

networks:
  bifrost_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

